kind: Service
apiVersion: v1
metadata:
  name: dockerreactdemo
  labels:
    app: dockerreactdemo
    visualize: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    app: dockerreactdemo
    serving: "true"
